import Foundation

/// Detects clinical-advice phrasings in German text generated by Gemma and
/// provides the fixed redirect message specified in the project brief.
///
/// Begleiter is positioned **below the MDR Class IIa threshold**: it is a
/// journaling tool, not an advisory tool. The model is instructed not to
/// give medical recommendations, but model output can still drift. This
/// service is the safety net that runs **after** generation — any claim
/// that reads like advice is replaced with the canonical redirect.
///
/// Detection is intentionally pattern-based, not Gemma-based, so the
/// safety net itself can't fail in surprising ways:
/// - the patterns are exhaustively unit-tested
/// - they have zero runtime dependencies on the model
/// - false positives are acceptable (over-redirection is safer than
///   under-redirection in a regulated-adjacent context)
enum RefusalService {

    /// The fixed German redirect string from the project specification.
    /// Used verbatim when the system needs to refuse an out-of-scope ask.
    static let redirectMessage: String = """
        Diese Frage gehört zu Ihrem Behandlungsteam. \
        Das Tagebuch kann Ihnen helfen, sich darauf vorzubereiten — \
        möchten Sie diese als offene Frage für Ihren nächsten Besuch hinzufügen?
        """

    /// Returns `true` if `text` contains clinical-advice phrasings.
    ///
    /// The detection runs on the **lowercased** form of `text` (after
    /// stripping diacritics so "müssen" and "muessen" both match) and looks
    /// for any of the patterns in `cluePhrases`. A single match is enough.
    static func containsClinicalAdvice(_ text: String) -> Bool {
        let needle = foldedForMatching(text)
        for clue in cluePhrases {
            if needle.contains(clue) { return true }
        }
        return false
    }

    /// Replace any advice-shaped claim text with the redirect message,
    /// leaving non-advice text untouched. Used by BriefingService and
    /// HandoffService to scrub output before showing it to the parent.
    static func scrubbed(_ text: String) -> String {
        containsClinicalAdvice(text) ? redirectMessage : text
    }

    // MARK: - Internals

    /// Lowercased + diacritic-folded form used for matching. We keep
    /// the original `text` untouched so the surrounding code can render
    /// the original or the redirect, not a normalised string.
    private static func foldedForMatching(_ text: String) -> String {
        text
            .folding(options: [.diacriticInsensitive, .caseInsensitive], locale: Locale(identifier: "de"))
            .replacingOccurrences(of: "ß", with: "ss")
    }

    /// Phrases that indicate the text is giving advice rather than
    /// describing what happened. All entries must be in the folded form
    /// produced by `foldedForMatching` (lowercase, ß → ss, AND Unicode
    /// diacritic-folded which strips umlauts to plain vowels: ö → o,
    /// ü → u, ä → a). For words where users commonly transliterate
    /// umlauts as digraphs (e.g. "muessen" instead of "müssen") we ship
    /// both forms.
    private static let cluePhrases: [String] = [
        // Explicit modal recommendations
        "sie sollten",
        "ihr kind sollte",
        "sie mussen sofort",   // folded form of "müssen"
        "sie muessen sofort",  // transliterated form
        "ich empfehle",
        "wir empfehlen",
        "es wird empfohlen",
        // Direct ER/clinic routing instructions
        "rufen sie den notarzt",
        "rufen sie 112",
        "rufen sie 911",
        "fahren sie sofort",
        "fahren sie ins krankenhaus",
        "gehen sie in die notaufnahme",
        "suchen sie sofort",
        "begeben sie sich umgehend",
        // Clinical-judgement phrasings about labs / vitals
        "der wert ist gefahrlich",   // folded "gefährlich"
        "der wert ist gefaehrlich",  // transliterated
        "der wert ist besorgniserregend",
        "der wert ist kritisch",
        // Dose / dose-adjustment language
        "erhohen sie die dosis",     // folded "erhöhen"
        "erhoehen sie die dosis",    // transliterated
        "reduzieren sie die dosis",
        "geben sie eine zusatzliche",     // folded "zusätzliche"
        "geben sie eine zusaetzliche",    // transliterated
        // Diagnostic phrasing
        "das ist sehr wahrscheinlich",
        "das deutet auf eine",
    ]
}
